export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const SET_MINIMUM_DATE = 'SET_MINIMUM_DATE';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';

export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCESS'; 
export const LOAD_DATE_SUCCESS = 'LOAD_DATE_SUCCESS'; 
export const LOAD_DATE_ICON_SUCCESS = 'LOAD_DATE_ICON_SUCCESS';
export const UPDATE_DATE_SUCCESS = 'UPDATE_DATE_SUCCESS';
export const UPDATE_DATE_ICON_SUCCESS = 'UPDATE_DATE_ICON_SUCCESS';
export const DELETE_DATE_SUCCESS = 'DELETE_DATE_SUCCESS';
export const INSERT_DATE_SUCCESS = 'INSERT_DATE_SUCCESS';

// TODO need authentication here...